language: java
jdk:
- oraclejdk8
install: mvn --version
before_script: "./.travis.version_if_tag.sh"
after_success: "./.travis.deploy_if_tag.sh"
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: LxBf+LzoRJTu50JcvegltG2M6DelYnN/sJRXwiSVRzXs2vcmrokb5I/LW2ORw5dzf3j5LtHnBeiNdcgD5xh2dqDkBncpQK1yVvPHa75oeagdWYUMk6KQBERzkHmuepiEy52sJPD88fgq1Es0QHqd54tZH4vbs0SS3QgQwupxrlNfRkCOMp1M9y4oa9hrMpKeRG572HP/BEsXp5in5++r1MOWy6fKp6mS0PXlM4xbHrXx4hPgcJ9KVVjV4tWT64eOt0goWpPwQvh5M1aguX5THs+xAfZRUDl8iA1RrSEjAkdOAN+qJ0l2r/8XvRVg35dfKaIg5NOiJ+S6tXPsvTxu5I1K2vB39FzLNFwkAinE7FRmy/XxvVDw0QosAoeCG2O5n6+RlXXCSi6LJ+NH06B0MxE6eUN+BUgi28aG/mjtEbwUrYiHf4nh0jsm7k7efG4UBGZXqPNc1p1Lj4IEMWUOpscJXP77jZPLz9vYIdEz9jxd830SfcTptNZOg3UmwsqRJCGJOGaUGvhDl/RtL9j4HhJDzUmT/dbZ4E9hMaAkfmZMz+KtrdVk/rZRW2+cXdcMIg0+dvIBAz1Gh7N8uiEjJ4U7AlltR+szdj/ZbAKq5eT4BKB6KXW4apiR5BqsLAgDfHpbq1Ot+S/SzPOx+SiEQjMsBe34l8vdO9HAhujmSvM=
  - secure: b8wGdKqlOKUGuLjeHGKk7D5mgYHlqwOJAWHlgdsGpCpvz82YRSsYIoOLD8cNPiJ7Jt0I2f9cMY6q8DwDwYML48CGYlXy3UYvUzkMBRR6ZPbp9lJCiMscWGrLwNLhUF27uS+/ZlRzEyslhBLJH9EdCbfPDy+t9XSFR6q2b5kR+aNcyyVirU/0DMzIB7gNzillo1ZTZEP5KYu43Z5B8cVwD+tGKTrPweaNyhQkt24V/lnhgmp4AqRQ/YdtpqBG8NN2Zmi4bRZHhzgu4pBUETzPqtdPC0u5829scYjxv2BWLPbfffxbByUG5jXwZwwaPE35Ccw1NMZRfyaBv6GlOBYtHvXBb+0Azeo4GYUdTBsgI7xMClGJPoRKn9WIKDukFf35ZUdJwPjzfEQjNml7OMzzDdTzVLO4Uq6h035+gyB0AZ1p0/7EeEZl06ZU2FjUTtFQV+AOFH8twGUIFkzm84NOfwFhdzPIGGzKBf0O7UiybuggKds51Ts87qE6m1aekG2AWspTFPsfHfVmxM7tDQ9U+ZoR+bHIkKj4OHmXRx4Xfg3cUBsKI8CSu9t3QQXdfSW+EzdQ4a7n9PKXYXZRCG+14tgVGwf4IaE4AXqCC5352LwIUA2AtKOX4CCgUWrGSCn3oJMm7lBQOe08Au5JfbqgQZSFiL72GmmOKGyXYhwkEuE=
deploy:
  provider: releases
  api_key:
    secure: z8WUgXfQXitqhGGit+/o/LoznTCGb6ggfzvxdmnhymq524ty+QNPyYRWLSSrauFqsWwM08WR8/GT6W5qohVMXIKhZSwnFubBD3c0YuQ9gucDJXkFe6Ej2ev0E4Nvnhrj2VQ0MVf0GribICOFn/kdGzghRJlqgRQ3PDHP3aO8pU2s9yNhcVkQsRHbEQll5AlQaDJLP24/szCfaGa87lb2ePxpOobGpjK9v/M9eZSTzESig/dp/M+nN8ZGKk81ER/NaF1IoK1nooNCKXeurIfc11Xs0gyESv9Lccc9cCXmkltQe8YRrliy9poGTHAZ38mYVynGH28p4E5pWn8zZguBiliMZ4HMtNNPTGLNlAR4bq3QkO+qMA+fZp+a/jvYnZ+EUnovXY9sWVU3oQdQtDQz95abBg1qeVFmA+V2P3tFA5o5JNk8aikh19mew9gY4ZAZ5ch9Xs/hRqIhgiAqTTD3m3E9F/AGHntdtu1Mj2bRaQLatVNRjLFP22OeOoB/vIP4NypBP34lofhrZpG6WFza1ZXjgCDronUvJRhSJgomnETYWvdpdm14G5k7Mh4eSuv39y4S/SQ4GToynSWv5gj9bjweJ66cw+UsHfPzMogY0i3XzzyGEd8ucvvt14GBXTIO1l32IDQ2wYzS8m5Fx1xJAEbwQ7xhYuKacuPpyhnixvs=
  file: nomer.jar
  skip_cleanup: true
  on:
    repo: globalbioticinteractions/nomer
    tags: true
